# Generated by Django 2.2.28 on 2025-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='How did you know about us?')),
                ('university_faculty', models.CharField(blank=True, max_length=255, null=True, verbose_name='University Faculty')),
                ('event_topics', models.TextField(blank=True, null=True, verbose_name='What topics would you like to be discussed in the event?')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo Code')),
                ('career_track', models.CharField(blank=True, max_length=100, null=True, verbose_name='Career Track')),
                ('identity', models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('other', 'Other')], max_length=20, null=True, verbose_name='Please choose one of the below, You are ...')),
                ('aiesecer', models.BooleanField(default=False, verbose_name='Are you an AIESECER?')),
            ],
        ),
    ]
