# Generated by Django 5.0.6 on 2025-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='aiesecer',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='career_track',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event_topics',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='university_faculty',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Twitter/X', 'Twitter/X'), ('TikTok', 'TikTok'), ('Email Newsletter', 'Email Newsletter'), ('Friend', 'Friend'), ('AIESEC Member', 'AIESEC Member'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_aiesecer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='topics_interested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
