# Generated by Django 5.0.6 on 2025-03-07 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registration_promo_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
